# Generated by Django 4.1.7 on 2024-06-13 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("content", "0024_remove_texteditorpost_click_count_and_more"),
        ("point", "0006_systempoint_task"),
        ("product", "0006_alter_product_category_category_name"),
        ("blacklist", "0002_alter_blacklist_blacklist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_created=True, auto_now_add=True, null=True
                    ),
                ),
                ("content", models.TextField(default="test content")),
                ("read", models.BooleanField(default=False)),
                ("desable", models.BooleanField(default=False)),
                (
                    "blacklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blacklist.blacklist",
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.texteditorpostcomment",
                    ),
                ),
                (
                    "exchange",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="point.exchange"
                    ),
                ),
                (
                    "gift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="point.gift"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.texteditorpost",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
                (
                    "systemPoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="point.systempoint",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
