# Generated by Django 4.1.7 on 2024-06-13 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("point", "0006_systempoint_task"),
        ("content", "0024_remove_texteditorpost_click_count_and_more"),
        ("product", "0006_alter_product_category_category_name"),
        ("blacklist", "0002_alter_blacklist_blacklist"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notifications",
            name="blacklist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blacklist.blacklist",
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.texteditorpostcomment",
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="exchange",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="point.exchange",
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="gift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="point.gift",
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.texteditorpost",
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="systemPoint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="point.systempoint",
            ),
        ),
    ]
