# Generated by Django 4.1.7 on 2024-06-13 17:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_alter_notifications_blacklist_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notifications",
            name="desable",
        ),
    ]
