# Generated by Django 4.1.7 on 2024-08-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blacklist", "0002_alter_blacklist_blacklist"),
    ]

    operations = [
        migrations.AddField(
            model_name="blacklist",
            name="updated_at",
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True),
        ),
    ]
