# Generated by Django 4.1.7 on 2024-08-19 16:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blacklist", "0003_blacklist_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blacklist",
            name="updated_at",
            field=models.DateTimeField(auto_created=True, auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name="Ban",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        auto_created=True,
                        blank=True,
                        default=datetime.datetime(2024, 8, 20, 16, 20, 42, 984017),
                        null=True,
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        auto_created=True, auto_now_add=True, null=True
                    ),
                ),
                (
                    "blacklist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blacklist.blacklist",
                    ),
                ),
            ],
        ),
    ]
