# Generated by Django 4.1.7 on 2024-09-05 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blacklist", "0004_alter_blacklist_updated_at_ban"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ban",
            name="blacklist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blacklist.blacklist"
            ),
        ),
        migrations.AlterField(
            model_name="ban",
            name="end_time",
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
