# Generated by Django 4.1.7 on 2023-08-29 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0002_rename_exchage_exchange_delete_pointrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gift',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='point',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=datetime.date.today),
            preserve_default=False,
        ),
    ]
