# Generated by Django 4.1.7 on 2023-12-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0003_alter_exchange_created_at_alter_gift_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
