# Generated by Django 4.1.7 on 2023-12-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0005_systempoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='systempoint',
            name='task',
            field=models.CharField(default='system_task', max_length=255),
        ),
    ]
