# Generated by Django 4.1.7 on 2024-10-24 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_alter_product_category_category_name"),
        ("point", "0006_systempoint_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exchange",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="exchange",
            name="point",
        ),
        migrations.RemoveField(
            model_name="exchange",
            name="product",
        ),
        migrations.CreateModel(
            name="exchangeProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_created=True, auto_now_add=True),
                ),
                ("amount", models.IntegerField(default=0)),
                ("point", models.IntegerField(default=0)),
                (
                    "exchange",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange",
                        to="point.exchange",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productExchage",
                        to="product.product",
                    ),
                ),
            ],
        ),
    ]
