# Generated by Django 4.1.7 on 2023-08-29 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='user_image/')),
                ('nickname', models.CharField(max_length=255, unique=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='bodyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('family_planning', models.CharField(blank=True, max_length=255, null=True)),
                ('expecting', models.CharField(blank=True, max_length=255, null=True)),
                ('medical_history', models.CharField(blank=True, max_length=255, null=True)),
                ('other_medical_history', models.TextField(blank=True, null=True)),
                ('medication', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor_advice', models.TextField(blank=True, null=True)),
                ('allergy', models.CharField(blank=True, max_length=255, null=True)),
                ('marriage', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
