# Generated by Django 4.1.7 on 2023-08-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_bodyprofile_expecting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfamilyplanning',
            name='user',
        ),
        migrations.AlterField(
            model_name='bodyprofile',
            name='expecting',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bodyprofile',
            name='family_planning',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='userExpecting',
        ),
        migrations.DeleteModel(
            name='userFamilyPlanning',
        ),
    ]
