# Generated by Django 4.1.7 on 2023-09-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_remove_userfamilyplanning_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='page_music',
            field=models.FileField(blank=True, null=True, upload_to='user_page_music/'),
        ),
    ]
