# Generated by Django 4.1.7 on 2023-09-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_bodyprofile_created_at_profile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_name',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
    ]
