# Generated by Django 4.1.7 on 2023-09-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_profile_email_profile_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
