# Generated by Django 4.1.7 on 2023-09-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_alter_profile_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_image/'),
        ),
    ]
