# Generated by Django 4.1.7 on 2023-10-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_alter_profile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_rd',
            field=models.BooleanField(default=False),
        ),
    ]
