# Generated by Django 4.1.7 on 2023-10-16 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0010_profile_is_rd'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='suscribe',
            field=models.ManyToManyField(blank=True, related_name='suscribe', to=settings.AUTH_USER_MODEL),
        ),
    ]
