# Generated by Django 4.1.7 on 2023-10-16 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0011_profile_suscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='suscribe',
        ),
        migrations.AddField(
            model_name='profile',
            name='subscribe',
            field=models.ManyToManyField(blank=True, related_name='subscribe', to=settings.AUTH_USER_MODEL),
        ),
    ]
