# Generated by Django 4.1.7 on 2023-10-19 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0012_remove_profile_suscribe_profile_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='personal_calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('cycle', models.IntegerField(default=0)),
                ('date', models.DateField(blank=True, null=True)),
                ('cycle_days', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
