# Generated by Django 4.1.7 on 2023-10-19 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_personal_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_calendar',
            name='type',
            field=models.CharField(blank=True, choices=[('月經', '月經'), ('排卵', '排卵'), ('小產期', '小產期'), ('懷孕期', '懷孕期'), ('更年期', '更年期')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='subPersonalCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dict', models.JSONField(blank=True, null=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.personal_calendar')),
            ],
        ),
    ]
