# Generated by Django 4.1.7 on 2023-11-16 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_texteditorpost_index_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0014_alter_personal_calendar_type_subpersonalcalendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_calendar',
            name='type',
            field=models.CharField(blank=True, choices=[('menstruation', '月經'), ('miscarriage period', '小產期'), ('pregnancy', '懷孕期'), ('menopause', '更年期'), ('postpartum_period', '產後期')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='subscribeTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.ManyToManyField(blank=True, related_name='topic', to='content.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
