# Generated by Django 4.1.7 on 2024-12-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userprofile", "0016_subscribehashtag"),
    ]

    operations = [
        migrations.CreateModel(
            name="personal_menstrual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("next_date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
