# Generated by Django 4.1.7 on 2024-12-09 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("userprofile", "0017_personal_menstrual"),
    ]

    operations = [
        migrations.AddField(
            model_name="personal_menstrual",
            name="calendar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="userprofile.personal_calendar",
            ),
        ),
    ]
