# Generated by Django 4.1.7 on 2024-05-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_status_blacklist_created_at_blacklist_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="desable",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Blacklist",
        ),
        migrations.DeleteModel(
            name="Status",
        ),
    ]
