# Generated by Django 4.1.7 on 2023-08-29 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='CommentImage/')),
            ],
        ),
        migrations.CreateModel(
            name='CommentVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('videos', models.FileField(blank=True, null=True, upload_to='CommentVideo/')),
            ],
        ),
        migrations.CreateModel(
            name='PostCommentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TextEditorPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('content', django_quill.fields.QuillField()),
                ('like', models.PositiveIntegerField(default=0)),
                ('share', models.PositiveIntegerField(default=0)),
                ('comment', models.PositiveIntegerField(default=0)),
                ('click', models.PositiveIntegerField(default=0)),
                ('bookmark', models.PositiveIntegerField(default=0)),
                ('desable', models.BooleanField(default=False)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(blank=True, default='test category', to='content.category')),
            ],
        ),
        migrations.CreateModel(
            name='TextEditorPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('body', models.TextField()),
                ('desable', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(blank=True, to='content.commentimage')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textEditorPostComments', to='content.texteditorpost')),
                ('videos', models.ManyToManyField(blank=True, to='content.commentvideo')),
            ],
        ),
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='content.category')),
            ],
        ),
        migrations.AddField(
            model_name='commentvideo',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testCommentVideo', to='content.texteditorpostcomment'),
        ),
        migrations.AddField(
            model_name='commentimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testCommentImages', to='content.texteditorpostcomment'),
        ),
    ]
