# Generated by Django 4.1.7 on 2023-08-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='texteditorpostcomment',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
