# Generated by Django 4.1.7 on 2023-10-15 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0003_alter_texteditorpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='texteditorpost',
            name='add_user',
            field=models.ManyToManyField(blank=True, related_name='add_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
