# Generated by Django 4.1.7 on 2023-10-15 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0004_texteditorpost_add_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texteditorpost',
            name='add_user',
        ),
        migrations.RemoveField(
            model_name='texteditorpost',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='texteditorpost',
            name='bookmark',
        ),
        migrations.RemoveField(
            model_name='texteditorpost',
            name='click',
        ),
        migrations.RemoveField(
            model_name='texteditorpost',
            name='like',
        ),
        migrations.RemoveField(
            model_name='texteditorpost',
            name='share',
        ),
        migrations.AddField(
            model_name='texteditorpost',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='bookmark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='texteditorpost',
            name='click',
            field=models.ManyToManyField(blank=True, related_name='click', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='texteditorpost',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='texteditorpost',
            name='share',
            field=models.ManyToManyField(blank=True, related_name='share', to=settings.AUTH_USER_MODEL),
        ),
    ]
