# Generated by Django 4.1.7 on 2023-10-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_texteditorpost_add_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='texteditorpost',
            name='identity',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
