# Generated by Django 4.1.7 on 2023-10-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_texteditorpost_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texteditorpost',
            name='identity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
