# Generated by Django 4.1.7 on 2023-10-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_texteditorpost_is_official'),
    ]

    operations = [
        migrations.AddField(
            model_name='texteditorpost',
            name='index_image',
            field=models.ImageField(blank=True, null=True, upload_to='textEditorPost_index_image/'),
        ),
    ]
