# Generated by Django 4.1.7 on 2023-11-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_texteditorpost_index_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='texteditorpostcomment',
            name='identity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
