# Generated by Django 4.1.7 on 2023-11-21 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_hashtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='post',
        ),
    ]
