# Generated by Django 4.1.7 on 2023-11-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_texteditorpost_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='texteditorpost',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
