# Generated by Django 4.1.7 on 2023-11-26 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_texteditorpost_is_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='texteditorpost',
            old_name='is_published',
            new_name='is_temporary',
        ),
    ]
