# Generated by Django 4.1.7 on 2023-11-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_rename_is_published_texteditorpost_is_temporary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texteditorpost',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
    ]
