# Generated by Django 4.1.7 on 2024-04-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0016_alter_texteditorpost_is_temporary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="texteditorpost",
            name="category",
        ),
        migrations.AddField(
            model_name="texteditorpost",
            name="subcategory",
            field=models.ManyToManyField(
                blank=True, default="test subcategory", to="content.subcategory"
            ),
        ),
    ]
