# Generated by Django 4.1.7 on 2024-05-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_rename_subcategory_texteditorpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='texteditorpost',
            name='reading_time',
            field=models.IntegerField(default=0),
        ),
    ]
