# Generated by Django 4.1.7 on 2024-05-08 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0021_option_vote_polls_option_polls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='polls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.polls'),
        ),
        migrations.AlterField(
            model_name='polls',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.texteditorpost'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
