# Generated by Django 4.1.7 on 2024-05-13 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_alter_option_polls_alter_polls_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='polls',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='content.polls'),
        ),
    ]
