# Generated by Django 4.1.7 on 2024-06-28 17:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0024_remove_texteditorpost_click_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="texteditorpost",
            name="bookmark",
        ),
    ]
