# Generated by Django 4.1.7 on 2023-09-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrecord',
            name='progress',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(blank=True, choices=[('BEGGINER', 'beginner'), ('WEEKLY', 'weekly'), ('DAILY', 'daily'), ('EVENT', 'event')], default='', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='taskPorgress',
        ),
    ]
