# Generated by Django 4.1.7 on 2023-09-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_taskrecord_progress_alter_task_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
