# Generated by Django 4.1.7 on 2024-12-10 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0025_remove_texteditorpost_bookmark"),
        ("task", "0003_alter_task_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="specify_content",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.texteditorpost",
            ),
        ),
    ]
