# Generated by Django 4.1.7 on 2024-04-11 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0002_alter_contentbookmark_user_alter_contentclick_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poststoraged',
            name='post',
        ),
    ]
