# Generated by Django 4.1.7 on 2024-04-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_alter_texteditorpost_is_temporary'),
        ('userdetail', '0003_remove_poststoraged_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='poststoraged',
            name='post',
            field=models.ManyToManyField(blank=True, related_name='postStoraged', to='content.texteditorpost'),
        ),
    ]
