# Generated by Django 4.1.7 on 2024-05-13 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userdetail', '0004_poststoraged_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='userBannedDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banned_date', models.DateTimeField(auto_created=True, auto_now_add=True, null=True)),
                ('not_shown', models.BooleanField(default=False)),
                ('is_chat_banned', models.BooleanField(default=False)),
                ('not_shown_by_user', models.ManyToManyField(blank=True, related_name='not_shown_by_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
