# Generated by Django 4.1.7 on 2024-06-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userdetail", "0005_userbanneddetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbanneddetail",
            name="ban_duration_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userbanneddetail",
            name="ban_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
