# Generated by Django 4.1.7 on 2024-08-19 16:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userdetail", "0006_userbanneddetail_ban_duration_days_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentclick",
            name="post",
        ),
        migrations.RemoveField(
            model_name="contentclick",
            name="user",
        ),
        migrations.RemoveField(
            model_name="contentdislike",
            name="post",
        ),
        migrations.RemoveField(
            model_name="contentdislike",
            name="user",
        ),
        migrations.RemoveField(
            model_name="contentlike",
            name="post",
        ),
        migrations.RemoveField(
            model_name="contentlike",
            name="user",
        ),
        migrations.RemoveField(
            model_name="contentshare",
            name="post",
        ),
        migrations.RemoveField(
            model_name="contentshare",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userbanneddetail",
            name="not_shown_by_user",
        ),
        migrations.RemoveField(
            model_name="userbanneddetail",
            name="user",
        ),
        migrations.DeleteModel(
            name="contentBookmark",
        ),
        migrations.DeleteModel(
            name="contentClick",
        ),
        migrations.DeleteModel(
            name="contentDislike",
        ),
        migrations.DeleteModel(
            name="contentLike",
        ),
        migrations.DeleteModel(
            name="contentShare",
        ),
        migrations.DeleteModel(
            name="userBannedDetail",
        ),
    ]
