# Generated by Django 4.1.7 on 2023-08-29 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_category',
            name='category_image',
        ),
    ]
