# Generated by Django 4.1.7 on 2023-08-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_category_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_category',
            name='category_description',
        ),
        migrations.AlterField(
            model_name='product_category',
            name='category_name',
            field=models.CharField(choices=[('有-自然受孕', '有-正在嘗試自然受孕'), ('有-人工受孕', '有-正在進行人工受孕療程'), ('無-有懷孕需求', '無-未來有懷孕需求'), ('懷孕<6', '小於六個月'), ('懷孕>6', '大於六個月'), ('病史-便秘', '便秘')], default='無-有懷孕需求', max_length=100),
        ),
    ]
