# Generated by Django 4.1.7 on 2023-08-29 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_category_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_category',
            name='category_product',
        ),
    ]
