# Generated by Django 4.1.7 on 2023-08-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_category_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ManyToManyField(blank=True, related_name='product_category', to='product.product_category'),
        ),
    ]
