# Generated by Django 4.1.7 on 2023-08-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_category',
            name='category_name',
            field=models.CharField(max_length=100),
        ),
    ]
