# Generated by Django 4.1.7 on 2024-10-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_alter_product_category_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
